// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDblGmdofbznxfyZhq_5ZGQi49O8JTWhuU',
    appId: '1:189468196444:web:b61a1d46686565065cf099',
    messagingSenderId: '189468196444',
    projectId: 'mydate-ec086',
    authDomain: 'mydate-ec086.firebaseapp.com',
    storageBucket: 'mydate-ec086.firebasestorage.app',
    measurementId: 'G-D0BSQPN7VL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUH6F4DSD8xC3gDI0Vr7pj7CTasfhRCfw',
    appId: '1:189468196444:android:005d2af85c1216595cf099',
    messagingSenderId: '189468196444',
    projectId: 'mydate-ec086',
    storageBucket: 'mydate-ec086.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY5242FLaLQb3JCI_P5QzxLNelH1OtPWE',
    appId: '1:189468196444:ios:6ba70ea46d3804755cf099',
    messagingSenderId: '189468196444',
    projectId: 'mydate-ec086',
    storageBucket: 'mydate-ec086.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationMidtermMydate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY5242FLaLQb3JCI_P5QzxLNelH1OtPWE',
    appId: '1:189468196444:ios:6ba70ea46d3804755cf099',
    messagingSenderId: '189468196444',
    projectId: 'mydate-ec086',
    storageBucket: 'mydate-ec086.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationMidtermMydate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDblGmdofbznxfyZhq_5ZGQi49O8JTWhuU',
    appId: '1:189468196444:web:b9650328fab87ec25cf099',
    messagingSenderId: '189468196444',
    projectId: 'mydate-ec086',
    authDomain: 'mydate-ec086.firebaseapp.com',
    storageBucket: 'mydate-ec086.firebasestorage.app',
    measurementId: 'G-3G9RD3PF73',
  );

}